project_id                         = "fluent-potion-419017"
workload_identity_pool_id          = "github"
workload_identity_pool_provider_id = "github"
service_account_id                 = "github"
docker_repo_location               = "northamerica-northeast2"