org_name                             = "georg"
workspace_name                       = "tfc-demo"
workspace_vcs_repo_branch            = "main"
workspace_vcs_repo_identifier        = "georgech91/tfc-demo"
workspace_vcs_repo_working_directory = "./infra"
project_name                         = "tfc-demo"
service_provider                     = "github"
tags_regex                           = "^deploy-\\d+.\\d+.\\d+$"
