name: Onboard TFC Workspace
on: [workflow_dispatch]
env:
  TF_WORKING_DIR: "./workspace-onboarding"
  ALLMYSECRETS: ${{ toJSON(secrets) }}
jobs:
  terraform:
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Check out repository
        uses: actions/checkout@v4
      - run: echo "${{ env.ALLMYSECRETS }}"
      # - id: setup
      #   name: Set up terraform
      #   uses: hashicorp/setup-terraform@v3
      #   with:
      #     cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      # - name: Terraform Init
      #   id: init
      #   run: terraform init
      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan
      # - name: Terraform Apply
      #   id: apply
      #   run: terraform apply -auto-approve